# Generated by Django 5.0.3 on 2026-04-21 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modelName', models.CharField(db_column='modelName', max_length=255)),
                ('prediction', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('transaction', models.OneToOneField(db_column='transactionId', on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='api.transaction')),
            ],
            options={
                'db_table': 'ModelPrediction',
            },
        ),
        migrations.CreateModel(
            name='NormalizedMerchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rawName', models.CharField(db_column='rawName', max_length=255, unique=True)),
                ('normalizedName', models.CharField(db_column='normalizedName', max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('defaultCategory', models.ForeignKey(blank=True, db_column='categoryId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_merchants', to='api.category')),
                ('user', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized_merchants', to='api.user')),
            ],
            options={
                'db_table': 'NormalizedMerchant',
            },
        ),
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchantName', models.CharField(db_column='merchantName', max_length=255)),
                ('frequency', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('lastOccurredAt', models.DateTimeField(db_column='lastOccurredAt')),
                ('nextExpectedAt', models.DateTimeField(db_column='nextExpectedAt')),
                ('confidence', models.FloatField()),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to='api.user')),
            ],
            options={
                'db_table': 'RecurringPattern',
            },
        ),
        migrations.CreateModel(
            name='InsightSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('expiresAt', models.DateTimeField(blank=True, db_column='expiresAt', null=True)),
                ('isRead', models.BooleanField(db_column='isRead', default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='insight_snapshots', to='api.user')),
            ],
            options={
                'db_table': 'InsightSnapshot',
                'indexes': [models.Index(fields=['user'], name='insight_user_idx'), models.Index(fields=['kind'], name='insight_kind_idx')],
            },
        ),
    ]
