# Generated by Django 5.0.3 on 2026-04-21 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modelprediction_normalizedmerchant_recurringpattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTrainingRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurredAt', models.DateTimeField(db_column='occurredAt')),
                ('amount', models.FloatField()),
                ('descriptionRaw', models.TextField(db_column='descriptionRaw')),
                ('predictedCategory', models.CharField(blank=True, db_column='predictedCategory', max_length=255, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='ml_training_rows', to='api.user')),
            ],
            options={
                'db_table': 'MLTrainingRow',
                'indexes': [models.Index(fields=['user'], name='ml_training_user_idx')],
            },
        ),
    ]
