# Generated by Django 5.0.3 on 2026-04-27 13:54

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mltrainingrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_balance', 'Low Balance Prediction'), ('unusual_spend', 'Unusual Spend Detected'), ('weekend_warning', 'Weekend Overspend Warning'), ('subscription_due', 'Subscription Due Soon')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Alert',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('users_processed', models.IntegerField(default=0)),
                ('error_logs', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ModelRun',
            },
        ),
        migrations.CreateModel(
            name='PredictionCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_version', models.CharField(max_length=50)),
                ('trajectory_data', models.JSONField()),
                ('predicted_runout_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PredictionCache',
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_monthly_burn', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('weekend_overspend_ratio', models.FloatField(default=1.0)),
                ('salary_credit_date_expected', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('savings_consistency_score', models.FloatField(default=0.0)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'UserBehaviorProfile',
            },
        ),
        migrations.AlterUniqueTogether(
            name='recurringpattern',
            unique_together={('user', 'merchantName')},
        ),
        migrations.AddField(
            model_name='recurringpattern',
            name='confidence_score',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringpattern',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.RenameField(
            model_name='recurringpattern',
            old_name='nextExpectedAt',
            new_name='next_due_date',
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='next_due_date',
            field=models.DateField(db_column='nextExpectedAt', db_index=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='merchantName',
            field=models.CharField(db_column='merchantName', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'occurredAt'], name='tx_usr_occ_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'is_recurring'], name='tx_usr_rec_idx'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.user'),
        ),
        migrations.AddField(
            model_name='predictioncache',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.user'),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='user',
            field=models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to='api.user'),
        ),
        migrations.RemoveField(
            model_name='recurringpattern',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recurringpattern',
            name='confidence',
        ),

        migrations.AddIndex(
            model_name='predictioncache',
            index=models.Index(fields=['user', '-created_at'], name='PredictionC_userId_8adbab_idx'),
        ),
    ]
