# Generated by Django 5.0.3 on 2026-04-30 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alert_modelrun_predictioncache_userbehaviorprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.FloatField()),
                ('saved_amount', models.FloatField(default=0.0)),
                ('monthly_contribution', models.FloatField()),
                ('icon', models.CharField(blank=True, default='target', max_length=100, null=True)),
                ('color', models.CharField(blank=True, default='#38BDF8', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.user')),
            ],
            options={
                'db_table': 'Goal',
                'ordering': ['-created_at'],
            },
        ),
    ]
